project_name: CamoDiffusion

__base__:
  - config/dataset_352x352.yaml

model:
  name: model.net_GRNet.net
  params:
    class_num: 1
    mask_chans: 1

cond_uvit:
  name: model.net_GRNet.EmptyObject
  params:
    conditioning_klass: model.net_GRNet.EmptyObject

diffusion_model:
  name: model.SimpleDiffSef.CondGaussianDiffusion
  params:
    # #model指的是引用model
    model: #model
    image_size: 352
    channels: 1
    cond_channels: 3
    noise_d: 64
    num_sample_steps: 10
    clip_sample_denoised: True
    pred_objective: 'x0'
    loss_type: 'model.loss.structure_loss'

optimizer:
  name: torch.optim.AdamW
  params:
    lr: 1e-4

train_val_forward_fn: "model.train_val_forward.modification_train_val_forward"

train_dataset:
  name: dataset.data_val.PolypObjDataset
  params:
    boundary_modification: True

